psql -v ON_ERROR_STOP=1 \
    -v PG_USER="$PG_USER" \
    -v PG_DB="$PG_DB" \
<<-EOSQL
    CREATE USER :PG_USER;
    CREATE DATABASE :PG_DB;
    GRANT ALL PRIVILEGES ON DATABASE :PG_DB TO :PG_USER;
EOSQL
